config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'login', to: "login#index"
  post 'get_login', to: "login#get_login"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "master/stores#index"

  # master
  namespace :master do
    resources :categories
    resources :stores, only: [:index, :show, :new, :create, :edit, :update]
  end

  # transaction
  get 'transaction/retrieve_stores', to: "transaction#retrieve_stores"
  get 'transaction/retrieve_transactions', to: "transaction#retrieve_transactions"
  post 'transaction/add_transaction', to: 'transaction#add_transaction'

  # client
  post 'client/verify_client', to: 'client#verify_client'
  post 'client/register_client', to: 'client#register_client'

  # dashboard
  post 'dashboard/retrieve_dashboard_data', to: 'dashboard#retrieve_dashboard_data'
end

app/models/master.rb
module Master
  def self.table_name_prefix
    "master_"
  end
end

app/models/master/category.rb
class Master::Category < ApplicationRecord
  validates :name, presence: true
  validates :status_id, presence: true
end

app/models/master/store.rb
class Master::Store < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3}
  validates :logo_url, presence: true, length: {minimum: 3}
  validates :category_id, presence: true
  
  belongs_to :master_category, :class_name => 'Master::Category', foreign_key: :category_id
end

app/controllers/master/categories_controller.rb
class Master::CategoriesController < ApplicationController
  layout 'dashboard'
  before_action :check_for_logged_in_session
  before_action :set_master_category, only: %i[ show edit update destroy ]

  # GET /master/categories or /master/categories.json
  def index
    @master_categories = Master::Category.all
  end

  # GET /master/categories/1 or /master/categories/1.json
  def show
  end

  # GET /master/categories/new
  def new
    @master_category = Master::Category.new
  end

  # GET /master/categories/1/edit
  def edit
  end

  # POST /master/categories or /master/categories.json
  def create
    @master_category = Master::Category.new(master_category_params)

    if @master_category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to "/master/categories"
      #format.html { redirect_to master_category_path(@master_category), notice: 'Category was successfully created.' }
      #format.json { render :show, status: :created, location: @master_category }
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @master_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /master/categories/1 or /master/categories/1.json
  def update
    if @master_category.update(master_category_params)
      flash[:notice] = 'Category was successfully updated.'
      redirect_to "/master/categories"
      # format.html { redirect_to master_category_path(@master_category), notice: 'Category was successfully updated.' }
      # format.json { render :show, status: :ok, location: @master_category }
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @master_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /master/categories/1 or /master/categories/1.json
  def destroy
    @master_category.destroy

    respond_to do |format|
      format.html { redirect_to master_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_master_category
    @master_category = Master::Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def master_category_params
    params.require(:master_category).permit(:name, :status_id)
  end
end

app/controllers/master/stores_controller.rb
class Master::StoresController < ApplicationController
  layout 'dashboard'
  before_action :check_for_logged_in_session
  before_action :set_master_store, only: [:show, :edit, :update]

  def index
    @master_stores = Master::Store.all
  end

  def show
  end

  def new
    @master_store = Master::Store.new
    @categories = Master::Category.all
  end

  def create
    @master_store = Master::Store.new(master_store_params)
    if @master_store.save
      flash[:notice] = "Created Successfully!"
      redirect_to "/"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @categories = Master::Category.all
  end

  def update
    if @master_store.update(master_store_params)
      flash[:notice] = "Updated Successfully!"
      redirect_to "/"
    else
      render 'edit'
    end
  end

  private

  def master_store_params
    params.require(:master_store).permit(:name, :logo_url, :category_id)
  end

  def set_master_store
    @master_store = Master::Store.find(params[:id])
  end
end

app/helpers/master/categories_helper.rb
module Master::CategoriesHelper
end

app/helpers/master/store_helper.rb
module Master::StoreHelper
end

app/helpers/master/stores_helper.rb
module Master::StoresHelper
end

app/views/master/categories/_form.html.erb
<%= form_with(model: master_category, class: "contents") do |form| %>
    <% if master_category.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
            <h2><%= pluralize(master_category.errors.count, "error") %> prohibited this master_category from being
                saved:</h2>

            <ul>
                <% master_category.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="my-5">
        <%= form.label :name %>
        <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
        <%= form.label :status_id %>
        <%= form.select :status_id, [["Published", 1], ["Draft", 2]], {}, { :class => "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-50 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" } %>
    </div>

    <div class="inline">
        <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
<% end %>

app/views/master/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", master_category: @master_category %>

  <%= link_to "Show this category", @master_category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to categories", master_categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/master/categories/index.html.erb
<div class="w-full">
    <div class="flex justify-between items-center m-3">
        <h1 class="font-bold text-4xl">Categories</h1>
        <%= link_to 'New category', new_master_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
    <div class="flex flex-col">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                            <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Edit</span>
                            </th>
                        </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">
                        <% @master_categories.each do |category| %>
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm font-medium text-gray-900"><%= category.name %></div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm font-medium text-gray-900"><%= category.status_id == 1 ? "Published" : "Draft" %></div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <%= link_to "Edit", edit_master_category_path(category.id), :class => "text-indigo-600 hover:text-indigo-900" %>
                                </td>
                            </tr>
                        <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/master/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", master_category: @master_category %>

  <%= link_to 'Back to categories', master_categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/master/categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @master_category %>

    <%= link_to 'Edit this master_category', edit_master_category_path(@master_category), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this master_category', master_category_path(@master_category), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to master_categories', master_categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>